#首先指定服务注册中心的地址为http://localhost:8761/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
##服务的端口为8769
server:
  port: 8769
##服务名为service-zuul
spring:
  application:
    name: service-zuul
zuul:
  routes:
    ##以/api-a/ 开头的请求都转发给service-ribbon服务
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    ##以/api-b/开头的请求都转发给service-feign服务
    api-b:
      path: /api-b/**
      serviceId: service-feign