server:
  port: 8045

spring:
  application:
    name: user_route

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.105:8848
        #namespace: 39e1e969-15f9-46d2-832d-fa052da55377
        #group: mall-user
#        cluster-name: BJ

dubbo:
  scan:
    # 指定 Dubbo 服务实现类的扫描基准包
    base-packages: com.tuling.mall.userconsumer
  application:
    name: ${spring.application.name}
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
#  registry:
#    #挂载到 Spring Cloud 注册中心  高版本可选
#    address: spring-cloud://192.168.1.104:8848