server:
  port: 8080
  
spring:
  redis:
    database: 0
    host: 192.168.124.10
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 200
        max-wait: 1000
        max-idle: 50
        min-idle: 10
    timeout:
      1000

  mvc:
    static-path-pattern: /**