server:
  port: 8766
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.229.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 920925
  application:
    ##注册到eureka server上的应用名称
    name: microservice-provider-user

eureka:
  client:
    service-url:
      ##与eureka server交互的地址，查询服务和注册服务都依赖这个地址
      defaultZone: http://admin:c9t5z2e7@localhost:8761/eureka/
    ##健康检查
    healthcheck:
      enabled: true
  instance:
    ##将ip配置到eureka server
    prefer-ip-address: true
    metadata-map:
      ##自定义元数据
      my-metadata: 我的元数据
    
info:
  app:
    name: project.artofactId@
    encoding: project.build.sourceEncoding@
    java:
      source: java.version
      target: java.target