spring:  application:    name: springboot-dubbo-provider-demo

server:
  port: 8801

dubbo:  scan:    base-packages: com.tuling.example  application:    name: springboot-dubbo-provider-demo  protocol:    name: dubbo    port: -1  registry:    id: nacos    address: 192.168.1.106    port: 8848    protocol: nacos